name: ubports-installer
version: '0.0.1'
summary: GUI installer for ubports devices
description: |
  This is an GUI installer for ubports ubuntu touch devices.

grade: devel
confinement: devmode

apps:
  ubports-installer:
    command: wrapper
    plugs: [home, x11, unity7, network]
  cli:
    command: wrapper-cli

parts:
  android-tools:
    source: git@github.com:ubports/android-tools.git
    plugin: make
    build-packages:
      - gir1.2-glib-2.0
      - libglib2.0-dev
      - libssl-dev
      - zlib1g-dev
  ubports-installer:
    source: git@github.com:ubports/ubports-installer.git
    plugin: nodejs
    stage-packages:
      - gconf-service
      - gconf2
      - git
      - gvfs-bin
      - libasound2
      - libcap2
      - libgcrypt20
      - libgtk2.0-0
      - libnotify4
      - libnss3
      - libudev1
      - libxtst6
      - python
      - xdg-utils
      - unity-gtk2-module
  electron:
    plugin: nodejs
    node-packages:
      - electron
  ubi-copy:
    source: ../bin
    plugin: copy
    files:
      snap-wrapper: bin/wrapper
      snap-wrapper-cli: bin/wrapper-cli
